version: '3.8'
services:
  nats-server:
    image: nats:latest
    container_name: nats-server
    ports:
      - "4222:4222"
    networks:
      - camera_network

  camera1:
    build:
      context: .
      dockerfile: Dockerfile.camera
    container_name: camera1
    environment:
      - VIDEO_DIRECTORY=${VIDEO_DIRECTORY1}
      - NATS_URL=${NATS_URL}
      - FRAME_GROUP=frames_group_1
      - Alarm_Num=Alarm_1
    depends_on:
      - nats-server
    volumes:
      - ./video_sets/set_1:/video_sets/set_1
      - .:/app
    working_dir: /app
    command: python camera.py
    networks:
      - camera_network

  camera2:
    build:
      context: .
      dockerfile: Dockerfile.camera
    container_name: camera2
    environment:
      - VIDEO_DIRECTORY=${VIDEO_DIRECTORY2}
      - NATS_URL=${NATS_URL}
      - FRAME_GROUP=frames_group_1
      - Alarm_Num=Alarm_2
    depends_on:
      - nats-server
    volumes:
      - ./video_sets/set_2:/video_sets/set_2
      - .:/app
    working_dir: /app
    command: python camera.py
    networks:
      - camera_network

  camera3:
    build:
      context: .
      dockerfile: Dockerfile.camera
    container_name: camera3
    environment:
      - VIDEO_DIRECTORY=${VIDEO_DIRECTORY3}
      - NATS_URL=${NATS_URL}
      - FRAME_GROUP=frames_group_1
      - Alarm_Num=Alarm_3
    depends_on:
      - nats-server
    volumes:
      - ./video_sets/set_3:/video_sets/set_3
      - .:/app
    working_dir: /app
    command: python camera.py
    networks:
      - camera_network

  camera4:
    build:
      context: .
      dockerfile: Dockerfile.camera
    container_name: camera4
    environment:
      - VIDEO_DIRECTORY=${VIDEO_DIRECTORY4}
      - NATS_URL=${NATS_URL}
      - FRAME_GROUP=frames_group_2
      - Alarm_Num=Alarm_4
    depends_on:
      - nats-server
    volumes:
      - ./video_sets/set_4:/video_sets/set_4
      - .:/app
    working_dir: /app
    command: python camera.py
    networks:
      - camera_network

  camera5:
    build:
      context: .
      dockerfile: Dockerfile.camera
    container_name: camera5
    environment:
      - VIDEO_DIRECTORY=${VIDEO_DIRECTORY5}
      - NATS_URL=${NATS_URL}
      - FRAME_GROUP=frames_group_2
      - Alarm_Num=Alarm_5
    depends_on:
      - nats-server
    volumes:
      - ./video_sets/set_5:/video_sets/set_5
      - .:/app
    working_dir: /app
    command: python camera.py
    networks:
      - camera_network

  edge-service1:
    build:
      context: .
      dockerfile: Dockerfile.edge
    container_name: edge-service1
    environment:
      - NATS_URL=${NATS_URL}
      - FRAME_GROUP=frames_group_1
    depends_on:
      - nats-server
    volumes:
      - .:/app
    working_dir: /app
    command: python edge_processor.py
    networks:
      - camera_network

  edge-service2:
    build:
      context: .
      dockerfile: Dockerfile.edge
    container_name: edge-service2
    environment:
      - NATS_URL=${NATS_URL}
      - FRAME_GROUP=frames_group_2
    depends_on:
      - nats-server
    volumes:
      - .:/app
    working_dir: /app
    command: python edge_processor.py
    networks:
      - camera_network

networks:
  camera_network:
    driver: bridge
