FROM python:3.9-slim

# Install dependencies
RUN pip install opencv-python-headless nats-py numpy python-dotenv

# Set working directory
WORKDIR /app

# Copy application code
COPY . .

# Default command for the edge service
CMD ["python", "edge_processor.py"]